name: routine
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.11+1


environment:
  sdk: ">=2.17.5 <3.0.0"

flutter_native_splash:
  image: "images/name.PNG"
  color: "4DD0E1"
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_auth: 4.1.0
  firebase_core: 2.1.1
  firebase_dynamic_links: 5.0.3
  cloud_firestore: ^4.0.4
  firebase_storage: 11.0.3
  firebase_messaging: 14.0.3
  cloud_functions: 4.0.3
  intl: ^0.17.0
  after_layout: ^1.0.7+2
  cupertino_icons: ^1.0.2
  photo_view: ^0.12.0
  path_provider: ^2.0.1
  image_picker: ^0.7.4
  matrix_gesture_detector: ^0.1.0
  url_launcher: ^6.1.5
  flutter_email_sender: ^5.1.0
  in_app_review: ^2.0.4
  shared_preferences: ^2.0.15
  #  google_mobile_ads: ^1.3.0
  flutter_ringtone_player: ^3.2.0
  share: ^2.0.4
  flutter_launcher_icons: ^0.9.3
  app_tracking_transparency: ^2.0.2+4
  syncfusion_flutter_calendar: ^20.3.49
  table_calendar: ^3.0.7
  numberpicker: ^2.1.1
  infinite_listview: ^1.1.0
  number_picker_dialog: ^0.0.1
  mobile_number_picker: ^0.0.1+5
  awesome_number_picker: ^0.0.4
  flutter_number_picker: ^1.0.4
  flutter_iconpicker: ^3.2.2
  flutter_tts: ^3.6.1
  flutter_local_notifications: ^12.0.3+1
  flutter_background_service: ^2.4.6
  dropdown_button2: ^1.8.9
  volume_control: ^0.1.5
  flutter_background: ^1.1.0
  device_info_plus: ^4.0.0
  audioplayers: ^2.0.0
  #  assets_audio_player: ^3.0.6
  just_audio_background: ^0.0.1-beta.9
  just_audio: ^0.9.31
  audio_service: ^0.18.9
  flutter_seekbar: ^0.0.1
  flutter_android: ^0.8.0
#  audio_manager: ^0.8.2
#  background_stt: ^1.0.6
adaptive_action_sheet: ^2.0.1
app_review: ^2.1.1
flutter_email_sender: ^5.1.0
admob_flutter: ^1.0.0
shared_preferences: ^2.0.15
#google_mobile_ads: ^1.3.0
audioplayers: ^0.19.1
flutter_launcher_icons: ^0.9.3
intl: ^0.17.0
table_calendar: ^3.0.0
share: ^2.0.4
provider: ^6.0.1
firebase_core_platform_interface: 4.5.1
just_audio: any # substitute version number
just_audio_background: any # substitute version number

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - music/


flutter_icons:
  android: true
  ios: true
  image_path: "images/name.PNG"
